force-app/main/default/objects/Codigo_de_Reembolso__c/Codigo_de_Reembolso__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Código de Reembolso</label>
</CustomObject>

force-app/main/default/objects/Codigo_de_Reembolso__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/Despesa_e_Reembolso__c.object-meta.xml
<CustomObject>
    <label>Despesa e Reembolso</label>
    <nameField>
        <label>Nome de Despesa e Reembolso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas e Reembolsos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Check_in__c.field-meta.xml
<CustomField>
    <fullName>Check_in__c</fullName>
    <label>Check-in</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Data_da_Visita__c.field-meta.xml
<CustomField>
    <fullName>Data_da_Visita__c</fullName>
    <formula>DATEVALUE(Check_in__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data da Visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Duracao_da_Visita__c.field-meta.xml
<CustomField>
    <fullName>Duracao_da_Visita__c</fullName>
    <label>Duração da Visita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Hora_da_Visita__c.field-meta.xml
<CustomField>
    <fullName>Hora_da_Visita__c</fullName>
    <formula>TIMEVALUE(Check_in__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hora da Visita</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Km__c.field-meta.xml
<CustomField>
    <fullName>Km__c</fullName>
    <inlineHelpText>Inserir os km que foram rodados e devem ser reembolsados. Obrigatório caso o tipo de reembolso seja &quot;Kilometragem&quot;</inlineHelpText>
    <label>Km</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Motivo_da_Recusa__c.field-meta.xml
<CustomField>
    <fullName>Motivo_da_Recusa__c</fullName>
    <label>Motivo da Recusa</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Nome_da_Empresa__c.field-meta.xml
<CustomField>
    <fullName>Nome_da_Empresa__c</fullName>
    <formula>IF(Conta__c != null, Conta__r.Name, IF(Prospect__c != null, Prospect__r.Name, Lead__r.FirstName + &apos; &apos; + Lead__r.LastName ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome da Empresa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Nome_do_Consultor__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Consultor__c</fullName>
    <formula>CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome do Consultor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>EnviadoParaRelatorio</fullName>
                <label>Enviado para o Relatório</label>
            </value>
            <value>
                <fullName>Recusado</fullName>
                <label>Recusado Pelo Gestor</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
                <label>Aprovado Pelo Gestor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Tipo_de_Despesa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Despesa__c</fullName>
    <label>Tipo de Despesa</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Despesa</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Valor_do_Reembolso_de_KM__c.field-meta.xml
<CustomField>
    <fullName>Valor_do_Reembolso_de_KM__c</fullName>
    <description>O valor calculado é referente aos KMs inseridos no registro multiplicado por R$0,91.</description>
    <formula>(Km__c * 0.91)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor do Reembolso de KM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultor</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Gerente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CR__c.field-meta.xml
<CustomField>
    <fullName>CR__c</fullName>
    <label>CR</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Matricula__c.field-meta.xml
<CustomField>
    <fullName>Matricula__c</fullName>
    <label>Matrícula</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <defaultValue>&quot;Sao Paulo Capital&quot;</defaultValue>
    <label>Unidade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Administração Pública DF</fullName>
            </value>
            <value>
                <fullName>Agronegócio</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Aracaju</fullName>
            </value>
            <value>
                <fullName>Atendimento ao Cliente</fullName>
            </value>
            <value>
                <fullName>Barueri</fullName>
            </value>
            <value>
                <fullName>Bauru</fullName>
            </value>
            <value>
                <fullName>Camaçari</fullName>
            </value>
            <value>
                <fullName>Campinas</fullName>
            </value>
            <value>
                <fullName>Central Nacional de Licitações</fullName>
            </value>
            <value>
                <fullName>CIEE em Movimento</fullName>
            </value>
            <value>
                <fullName>CIEE One</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>Feira de Santana</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Fortaleza</fullName>
            </value>
            <value>
                <fullName>Goiás</fullName>
            </value>
            <value>
                <fullName>GR Centro-Oeste e Norte</fullName>
            </value>
            <value>
                <fullName>GR Grande SP e Capital</fullName>
            </value>
            <value>
                <fullName>GR Nordeste</fullName>
            </value>
            <value>
                <fullName>GR SP Interior e BH</fullName>
            </value>
            <value>
                <fullName>Guarulhos</fullName>
            </value>
            <value>
                <fullName>Inclusão Social</fullName>
            </value>
            <value>
                <fullName>Itabuna</fullName>
            </value>
            <value>
                <fullName>Itapetininga</fullName>
            </value>
            <value>
                <fullName>João Pessoa</fullName>
            </value>
            <value>
                <fullName>Juazeiro do Norte</fullName>
            </value>
            <value>
                <fullName>Jundiaí</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_Despesa.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>KM</fullName>
    </customValue>
    <customValue>
        <fullName>Outras despesas</fullName>
        <isActive>false</isActive>
        <label>Outras despesas</label>
    </customValue>
    <masterLabel>Tipo de Despesa</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AprovacaoDespesasReembolsosController.cls
public class AprovacaoDespesasReembolsosController {
    private static final Codigo_de_Reembolso__c CODIGO_REEMBOLSO = Codigo_de_Reembolso__c.getOrgDefaults();
    private static final String[] USER_FIELDS = new List<String>{ 'Id', 'Unidade__c', 'Cargo__c', 'Profile.Name' };

    private static final String[] DESPESAS_FIELDS = new List<String>{
        'Id',
        'Name',
        'Data_da_Visita__c',
        'Duracao_da_Visita__c',
        'Hora_da_Visita__c',
        'Km__c',
        'Nome_da_Empresa__c',
        'Valor_do_Reembolso_de_KM__c',
        'Nome_do_Consultor__c',
        'CreatedById',
        'Check_In__c'
    };

    @AuraEnabled(cacheable=true)
    public static List<Despesa_e_Reembolso__c> buscarDados(String criador) {
        Boolean allUsers = String.isBlank(criador) || criador == 'Todos';
        Id userId = UserInfo.getUserId();

        String userQuery = 'SELECT ' + String.join(USER_FIELDS, ', ') + ' FROM User WHERE Id = :userId';

        User user = Database.query(userQuery);
        Boolean isAdmin = user.Profile.Name == 'Administrador do sistema' || user.Profile.Name == 'System Administrator';
        Boolean isSuperIntendencia = user.Profile.Name == 'Superintendência';
        Boolean isGerente = user.Cargo__c == 'Gerente';
        String unidade = user.Unidade__c;
        String cargo = user.Cargo__c;

        String query = 'SELECT ' + String.join(DESPESAS_FIELDS, ', ') + ' ';
        query += 'FROM Despesa_e_Reembolso__c ';
        query += 'WHERE Status__c = \'Enviado_para_o_Relatorio\' AND Tipo_de_Despesa__c = \'KM\'';

        if (isSuperIntendencia) {
            query += ' AND CreatedBy.Cargo__c = \'Gerente\' ';
        }

        if (!isAdmin && !isSuperIntendencia && !isGerente) {
            query += ' AND CreatedBy.Unidade__c = :unidade';
        }

        if (cargo == 'Gerente') {
            query += ' AND (CreatedBy.Unidade__c = :unidade OR CreatedBy.ManagerId = :userId)';
            query += ' AND (CreatedBy.Cargo__c = \'Supervisor\' OR CreatedBy.Cargo__c = \'Consultor\')';
        }

        if (cargo == 'Supervisor') {
            query += ' AND CreatedBy.Cargo__c = \'Consultor\'';
        }

        if (!allUsers) {
            query += ' AND CreatedBy.Name = :criador ';
        }

        System.debug(query);
        return Database.query(query);
    }

    @AuraEnabled
    public static String reprovarDespesaReembolso(List<Despesa_e_Reembolso__c> despesas, String motivo, String despesaNameRecusa) {
        System.debug('despesa' + despesaNameRecusa);
        System.debug('motivo' + motivo);

        for (Despesa_e_Reembolso__c despesa : despesas) {
            despesa.Status__c = 'Recusado';
            if (despesa.Name == despesaNameRecusa) {
                despesa.Motivo_da_Recusa__c = motivo;
            }
        }

        Database.update(despesas);

        return 'Sucesso';
    }

    @InvocableMethod(label = 'Integrar Despesas e Reembolsos')
    public static void aprovarDespesaReembolso(List<IntegrationParams> params) {

        List<Despesa_e_Reembolso__c> despesas = params[0].lstDespesas;

        User user = [
            SELECT Id, CPF__c, CR__c, Matricula__c, Name
            FROM User
            WHERE Id = :despesas[0].CreatedById
        ];

        String txtFile = String.format(
            'C|01|0001|U_CEAIA38|3|{0}|{1}|{2}|{3}|{4}\n',
            new List<Object>{ user.CPF__c, user.Matricula__c, user.Name, user.CR__c, (Integer) CODIGO_REEMBOLSO.Codigo__c }
        );

        String placeholder = 'I|{0}|{1}|{2}|{3}|{4}|{5}|0|0|0|0|0|{5}\n';

        for (Despesa_e_Reembolso__c despesa : despesas) {
            txtFile += String.format(
                placeholder,
                new List<Object>{
                    despesa.Check_In__c.format('yyyyMMdd'),
                    despesa.Check_in__c.format('HH:mm'),
                    despesa.Duracao_da_Visita__c,
                    despesa.Nome_da_Empresa__c,
                    despesa.Km__c,
                    Integer.valueOf(despesa.Valor_do_Reembolso_de_KM__c * 100)
                }
            );

            despesa.Status__c = 'Aprovado';
        }

        System.debug('txtFile:' + txtFile);

        System.enqueueJob(new UploadExpenseToAmazonS3(txtFile, (Integer) CODIGO_REEMBOLSO.Codigo__c + '.txt'));

        update despesas;

        CODIGO_REEMBOLSO.Codigo__c += 1;

        update CODIGO_REEMBOLSO;

       // return 'Sucesso';
    }

    public class IntegrationParams{
        @invocableVariable
        public List<Despesa_e_Reembolso__c> lstDespesas;
    }
}