force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <label>Nome de Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carteira__c/fields/Apoio__c.field-meta.xml
<CustomField>
    <fullName>Apoio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apoio</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Carteiras1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/AteOCEPSemFormatacao__c.field-meta.xml
<CustomField>
    <fullName>AteOCEPSemFormatacao__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE(Ate_o_CEP__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Até o CEP sem formatação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Carteira__c.field-meta.xml
<CustomField>
    <fullName>Carteira__c</fullName>
    <label>Carteira</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Carteiras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/DoCEPSemFormatacao__c.field-meta.xml
<CustomField>
    <fullName>DoCEPSemFormatacao__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE(Do_CEP__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Do CEP sem formatação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Apoio__c.field-meta.xml
<CustomField>
    <fullName>Apoio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apoio</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CEPSemFormatacao__c.field-meta.xml
<CustomField>
    <fullName>CEPSemFormatacao__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE(PostalCode, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEP sem formatação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public with sharing class LeadTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public static boolean IsFromBachJob;
    public static boolean isFromUploadAPI = false;

    public LeadTriggerHandler(boolean isExecuting, integer size) {
        m_isExecuting = isExecuting;
        BatchSize = size;
    }

    public void OnBeforeInsert(List<Lead> newLead) {
        List<Carteira__c> carteiras;

        if (newLead[0].CEPSemFormatacao__c != null) {
            carteiras = [
                SELECT Id, Consultor__c, DoCEPSemFormatacao__c, AteOCEPSemFormatacao__c, Apoio__C
                FROM Carteira__c
                WHERE DoCEPSemFormatacao__c <= :newLead[0].CEPSemFormatacao__c AND AteOCEPSemFormatacao__c >= :newLead[0].CEPSemFormatacao__c
                LIMIT 1
            ];

            if (carteiras.size() > 0) {
                newLead[0].OwnerId = carteiras[0].Apoio__c;
                newLead[0].Consultor__c = carteiras[0].Consultor__c;
            }
        }
        
        ZipCodeLead.setAssignedUserByPostalCode(newLead);
    }

    public void OnBeforeUpdate(List<Lead> newLead, List<Lead> oldLead, Map<ID, Lead> newLeadMap, Map<ID, Lead> oldLeadMap) {
        List<Carteira__c> carteiras;

        if (newLead[0].CEPSemFormatacao__c != null) {
            carteiras = [
                SELECT Id, Consultor__c, DoCEPSemFormatacao__c, AteOCEPSemFormatacao__c, Apoio__C
                FROM Carteira__c
                WHERE DoCEPSemFormatacao__c <= :newLead[0].CEPSemFormatacao__c AND AteOCEPSemFormatacao__c >= :newLead[0].CEPSemFormatacao__c
                LIMIT 1
            ];

            if (carteiras.size() > 0) {
                newLead[0].OwnerId = carteiras[0].Apoio__c;
                newLead[0].Consultor__c = carteiras[0].Consultor__c;
            }
        }
    }

    public void OnAfterInsert(List<Lead> newLead) {
    }

    public void OnAfterUpdate(List<Lead> newLead, List<Lead> oldLead, Map<ID, Lead> newLeadMap, Map<ID, Lead> oldLeadMap) {
    }
}