force-app/main/default/objects/ZipCode__c/ZipCode__c.object-meta.xml
<CustomObject>
    <label>ZipCode</label>
    <nameField>
        <displayFormat>Z-{0}</displayFormat>
        <label>ZipCode Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZipCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCode__c/fields/Assigned__c.field-meta.xml
<CustomField>
    <fullName>Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ZipCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipCode__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZipCodeLead.cls
public with sharing class ZipCodeLead {
    public static void setAssignedUserByPostalCode(List<Lead> leadList) {
        Set<String> zipcodesSet = new Set<String>();
        for (Lead l : leadList) {
            zipcodesSet.add(l.PostalCode);
        }

        Map<String, ZipCode__c> mapCepToZipCode = new Map<String, ZipCode__c>();
        for (ZipCode__c zc : [SELECT Id, Assigned__c, Zip_Code__c FROM ZipCode__c WHERE Zip_Code__c IN :zipcodesSet]) {
            mapCepToZipCode.put(zc.Zip_Code__c, zc);
        }

        for (Lead l : leadList) {
            l.OwnerId = mapCepToZipCode.containsKey(l.PostalCode) ? mapCepToZipCode.get(l.PostalCode).Assigned__c : l.OwnerId;
        }
    }
}