force-app/main/default/objects/Account/fields/Apoio__c.field-meta.xml
<CustomField>
    <fullName>Apoio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor de Atendimento</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEPSemFormatacao__c.field-meta.xml
<CustomField>
    <fullName>CEPSemFormatacao__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE(BillingPostalCode, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEP sem formatação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <label>Nome de Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carteira__c/fields/Apoio__c.field-meta.xml
<CustomField>
    <fullName>Apoio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apoio</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Carteiras1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/AteOCEPSemFormatacao__c.field-meta.xml
<CustomField>
    <fullName>AteOCEPSemFormatacao__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE(Ate_o_CEP__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Até o CEP sem formatação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Carteira__c.field-meta.xml
<CustomField>
    <fullName>Carteira__c</fullName>
    <label>Carteira</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Carteiras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/DoCEPSemFormatacao__c.field-meta.xml
<CustomField>
    <fullName>DoCEPSemFormatacao__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE(Do_CEP__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Do CEP sem formatação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public static boolean IsFromBachJob ;
    public static boolean isFromUploadAPI = false;
    
    public AccountTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    
    public void OnBeforeInsert(List<Account> newAccount){
        List<Carteira__c> carteiras;
        
        if(newAccount[0].CEPSemFormatacao__c!= null){
            carteiras = [SELECT Id, Consultor__c, DoCEPSemFormatacao__c, AteOCEPSemFormatacao__c,Apoio__C
                         FROM Carteira__c
                         WHERE DoCEPSemFormatacao__c <= :newAccount[0].CEPSemFormatacao__c
                         AND AteOCEPSemFormatacao__c >= :newAccount[0].CEPSemFormatacao__c 
                        LIMIT 1];
            
            if(carteiras.size() > 0){
         
                newAccount[0].OwnerId = carteiras[0].Apoio__c;
                newAccount[0].Consultor__c = carteiras[0].Consultor__c;
            }
        }
    }
    
    public void OnBeforeUpdate( List<Account> newAccount, List<Account> oldAccount, Map<ID, Account> newAccountMap , Map<ID, Account> oldAccountMap ){
        List<Carteira__c> carteiras;
        
        if(newAccount[0].CEPSemFormatacao__c!= null){
            carteiras = [SELECT Id, Consultor__c, DoCEPSemFormatacao__c, AteOCEPSemFormatacao__c,Apoio__C
                         FROM Carteira__c
                         WHERE DoCEPSemFormatacao__c <= :newAccount[0].CEPSemFormatacao__c
                         AND AteOCEPSemFormatacao__c >= :newAccount[0].CEPSemFormatacao__c 
                        LIMIT 1];
            
            if(carteiras.size() > 0){
                
                newAccount[0].OwnerId = carteiras[0].Apoio__c;
                newAccount[0].Consultor__c = carteiras[0].Consultor__c;
            }
        }
    }
    
    /*public void OnAfterInsert(List<Account> newAccount){
        AccountActions.insertAccountTeamMember(newAccount);
    }
    
    public void OnAfterUpdate(List<Account> newAccount, List<Account> oldAccount, Map<ID, Account> newAccountMap , Map<ID, Account> oldAccountMap){
        AccountActions.deleteAccountTeamMember(newAccount); 
        AccountActions.insertAccountTeamMember(newAccount);
    }*/
}