force-app/main/default/objects/Account/fields/Apoio__c.field-meta.xml
<CustomField>
    <fullName>Apoio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor de Atendimento</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <label>Unidade de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia_Regional__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Unidades_de_Atendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <label>Nome de Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carteira__c/fields/Apoio__c.field-meta.xml
<CustomField>
    <fullName>Apoio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apoio</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Carteiras1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Ate_o_CEP__c.field-meta.xml
<CustomField>
    <fullName>Ate_o_CEP__c</fullName>
    <inlineHelpText>XXXXX-XXX</inlineHelpText>
    <label>Até o CEP</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Carteira__c.field-meta.xml
<CustomField>
    <fullName>Carteira__c</fullName>
    <label>Carteira</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Carteiras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carteira__c/fields/Do_CEP__c.field-meta.xml
<CustomField>
    <fullName>Do_CEP__c</fullName>
    <inlineHelpText>XXXXX-XXX</inlineHelpText>
    <label>Do CEP</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <defaultValue>&quot;Sao Paulo Capital&quot;</defaultValue>
    <label>Unidade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Administração Pública DF</fullName>
            </value>
            <value>
                <fullName>Agronegócio</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Aracaju</fullName>
            </value>
            <value>
                <fullName>Atendimento ao Cliente</fullName>
            </value>
            <value>
                <fullName>Barueri</fullName>
            </value>
            <value>
                <fullName>Bauru</fullName>
            </value>
            <value>
                <fullName>Camaçari</fullName>
            </value>
            <value>
                <fullName>Campinas</fullName>
            </value>
            <value>
                <fullName>Central Nacional de Licitações</fullName>
            </value>
            <value>
                <fullName>CIEE em Movimento</fullName>
            </value>
            <value>
                <fullName>CIEE One</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>Feira de Santana</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Fortaleza</fullName>
            </value>
            <value>
                <fullName>Goiás</fullName>
            </value>
            <value>
                <fullName>GR Centro-Oeste e Norte</fullName>
            </value>
            <value>
                <fullName>GR Grande SP e Capital</fullName>
            </value>
            <value>
                <fullName>GR Nordeste</fullName>
            </value>
            <value>
                <fullName>GR SP Interior e BH</fullName>
            </value>
            <value>
                <fullName>Guarulhos</fullName>
            </value>
            <value>
                <fullName>Inclusão Social</fullName>
            </value>
            <value>
                <fullName>Itabuna</fullName>
            </value>
            <value>
                <fullName>Itapetininga</fullName>
            </value>
            <value>
                <fullName>João Pessoa</fullName>
            </value>
            <value>
                <fullName>Juazeiro do Norte</fullName>
            </value>
            <value>
                <fullName>Jundiaí</fullName>
            </value>
            <value>
                <fullName>São Paulo Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TesteTriggerAccount.cls
@isTest
public class TesteTriggerAccount {
    @isTest
    public static void criaContaComCarteira(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Usuário Padrão'];  
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@cieetest.com', Unidade__c='São Paulo Capital');
        insert u;
        Carteira__c carteira = new Carteira__C(Apoio__c = u.Id , Consultor__c = u.Id);
        carteira.Ate_o_CEP__c = '10000-000';
        carteira.Do_CEP__c = '00000-000';        
        insert carteira;
        Account acc = new Account();
        acc.Name = 'teste';
        acc.CNPJ_CPF__c = '61.600.839/0001-55'; 
        acc.BillingPostalCode = '01000-000';
        insert acc;
    }
    @isTest
    public static void atualizaContaComCarteira(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Usuário Padrão'];  
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@cieetest.com', Unidade__c='São Paulo Capital');
        insert u;
        Carteira__c carteira = new Carteira__C(Apoio__c = u.Id , Consultor__c = u.Id);
        carteira.Ate_o_CEP__c = '10000-000';
        carteira.Do_CEP__c = '00000-000';  
       
        insert carteira;
        Account acc = new Account();
        acc.Name = 'teste';
        acc.CNPJ_CPF__c = '61.600.839/0001-55'; 
        acc.BillingPostalCode = '01000-000';
        insert acc;
        acc.BillingPostalCode = '00100-000';
        update acc;
    }
}