force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <description>Segmentação CNAE (Classificação Nacional de Atividades Econômicas), nível &quot;Seção&quot;.</description>
    <inlineHelpText>Preencher de acordo com a primeira parte do código da atividade econômica principal.</inlineHelpText>
    <label>CNAE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01..03 AGRICULTURA PECUÁRIA PRODUÇÃO FLORESTAL PESCA E AQÜICULTURA</fullName>
                <label>01..03 AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA</label>
            </value>
            <value>
                <fullName>05..09 INDÚSTRIAS EXTRATIVAS</fullName>
            </value>
            <value>
                <fullName>10..33 INDÚSTRIAS DE TRANSFORMAÇÃO</fullName>
            </value>
            <value>
                <fullName>35..35 ELETRICIDADE E GÁS</fullName>
            </value>
            <value>
                <fullName>36..39 ÁGUA ESGOTO ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO</fullName>
                <label>36..39 ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO</label>
            </value>
            <value>
                <fullName>41..43 CONSTRUÇÃO</fullName>
            </value>
            <value>
                <fullName>45..47 COMÉRCIO REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS</fullName>
                <label>45..47 COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS</label>
            </value>
            <value>
                <fullName>49..53 TRANSPORTE ARMAZENAGEM E CORREIO</fullName>
                <label>49..53 TRANSPORTE, ARMAZENAGEM E CORREIO</label>
            </value>
            <value>
                <fullName>55..56 ALOJAMENTO E ALIMENTAÇÃO</fullName>
            </value>
            <value>
                <fullName>58..63 INFORMAÇÃO E COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>64..66 ATIVIDADES FINANCEIRAS DE SEGUROS E SERVIÇOS RELACIONADOS</fullName>
                <label>64..66 ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS</label>
            </value>
            <value>
                <fullName>68..68 ATIVIDADES IMOBILIÁRIAS</fullName>
            </value>
            <value>
                <fullName>69..75 ATIVIDADES PROFISSIONAIS CIENTÍFICAS E TÉCNICAS</fullName>
                <label>69..75 ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS</label>
            </value>
            <value>
                <fullName>77..82 ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES</fullName>
            </value>
            <value>
                <fullName>84..84 ADMINISTRAÇÃO PÚBLICA DEFESA E SEGURIDADE SOCIAL</fullName>
                <label>84..84 ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL</label>
            </value>
            <value>
                <fullName>85..85 EDUCAÇÃO</fullName>
            </value>
            <value>
                <fullName>86..88 SAÚDE HUMANA E SERVIÇOS SOCIAIS</fullName>
            </value>
            <value>
                <fullName>90..93 ARTES CULTURA ESPORTE E RECREAÇÃO</fullName>
                <label>90..93 ARTES, CULTURA, ESPORTE E RECREAÇÃO</label>
            </value>
            <value>
                <fullName>94..96 OUTRAS ATIVIDADES DE SERVIÇOS</fullName>
            </value>
            <value>
                <fullName>97..97 SERVIÇOS DOMÉSTICOS</fullName>
            </value>
            <value>
                <fullName>99..99 ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS</fullName>
            </value>
            <value>
                <fullName>Estudante</fullName>
            </value>
            <value>
                <fullName>Inapto</fullName>
            </value>
            <value>
                <fullName>ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL</fullName>
                <isActive>false</isActive>
                <label>ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL</label>
            </value>
            <value>
                <fullName>AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA</fullName>
                <isActive>false</isActive>
                <label>AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA</label>
            </value>
            <value>
                <fullName>ALOJAMENTO E ALIMENTAÇÃO</fullName>
                <isActive>false</isActive>
                <label>ALOJAMENTO E ALIMENTAÇÃO</label>
            </value>
            <value>
                <fullName>ARTES, CULTURA, ESPORTE E RECREAÇÃO</fullName>
                <isActive>false</isActive>
                <label>ARTES, CULTURA, ESPORTE E RECREAÇÃO</label>
            </value>
            <value>
                <fullName>ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES</fullName>
                <isActive>false</isActive>
                <label>ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES</label>
            </value>
            <value>
                <fullName>ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS</fullName>
                <isActive>false</isActive>
                <label>ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS</label>
            </value>
            <value>
                <fullName>ATIVIDADES IMOBILIÁRIAS</fullName>
                <isActive>false</isActive>
                <label>ATIVIDADES IMOBILIÁRIAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gerencia_Regional__c.field-meta.xml
<CustomField>
    <fullName>Gerencia_Regional__c</fullName>
    <label>Gerência Regional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gerencias_Regionais</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <label>Unidade de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia_Regional__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Unidades_de_Atendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/globalValueSets/Gerencias_Regionais.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>GR Grande São Paulo e Capital</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>GR SP Interior</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>GR Nordeste</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>GR Centro Oeste e Norte</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Ger CIEE Autônomo</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <isActive>false</isActive>
        <label>Ger Rio de Janeiro</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <isActive>false</isActive>
        <label>GR Norte</label>
    </customValue>
    <masterLabel>Gerências Regionais</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestRemoveFormattingCPFandCNPJ.cls
@isTest
public with sharing class TestRemoveFormattingCPFandCNPJ {
    @TestSetup
    static void makeData(){
        Account acc = new Account(
            Name = 'Teste',
            BillingPostalCode = '01000-000',
            CNPJ_CPF__c = '123.98/00-00',
            Gerencia_Regional__c = '1',
            CNAE__c = '01..03 AGRICULTURA PECUÁRIA PRODUÇÃO FLORESTAL PESCA E AQÜICULTURA',
            CNAE_Divisao__c = '01 AGRICULTURA PECUÁRIA E SERVIÇOS RELACIONADOS',
            Unidade__c = '101'
        );
        insert acc;
    }

    @isTest
    private static void testTestCase() {

        String accCpfCnpj = [SELECT CNPJ_CPF__c FROM Account LIMIT 1].CNPJ_CPF__c;

        Test.startTest();

        Database.executeBatch(new RemoveFormattingCPFandCNPJ());
    
        Test.stopTest();

        String accCpfCnpj2 = [SELECT CNPJ_CPF__c FROM Account LIMIT 1].CNPJ_CPF__c;

        Assert.areNotEqual(accCpfCnpj, accCpfCnpj2);
    }
}