force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <description>Segmentação CNAE (Classificação Nacional de Atividades Econômicas), nível &quot;Seção&quot;.</description>
    <inlineHelpText>Preencher de acordo com a primeira parte do código da atividade econômica principal.</inlineHelpText>
    <label>CNAE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01..03 AGRICULTURA PECUÁRIA PRODUÇÃO FLORESTAL PESCA E AQÜICULTURA</fullName>
                <label>01..03 AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA</label>
            </value>
            <value>
                <fullName>05..09 INDÚSTRIAS EXTRATIVAS</fullName>
            </value>
            <value>
                <fullName>10..33 INDÚSTRIAS DE TRANSFORMAÇÃO</fullName>
            </value>
            <value>
                <fullName>35..35 ELETRICIDADE E GÁS</fullName>
            </value>
            <value>
                <fullName>36..39 ÁGUA ESGOTO ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO</fullName>
                <label>36..39 ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO</label>
            </value>
            <value>
                <fullName>41..43 CONSTRUÇÃO</fullName>
            </value>
            <value>
                <fullName>45..47 COMÉRCIO REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS</fullName>
                <label>45..47 COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS</label>
            </value>
            <value>
                <fullName>49..53 TRANSPORTE ARMAZENAGEM E CORREIO</fullName>
                <label>49..53 TRANSPORTE, ARMAZENAGEM E CORREIO</label>
            </value>
            <value>
                <fullName>55..56 ALOJAMENTO E ALIMENTAÇÃO</fullName>
            </value>
            <value>
                <fullName>58..63 INFORMAÇÃO E COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>64..66 ATIVIDADES FINANCEIRAS DE SEGUROS E SERVIÇOS RELACIONADOS</fullName>
                <label>64..66 ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS</label>
            </value>
            <value>
                <fullName>68..68 ATIVIDADES IMOBILIÁRIAS</fullName>
            </value>
            <value>
                <fullName>69..75 ATIVIDADES PROFISSIONAIS CIENTÍFICAS E TÉCNICAS</fullName>
                <label>69..75 ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS</label>
            </value>
            <value>
                <fullName>77..82 ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES</fullName>
            </value>
            <value>
                <fullName>84..84 ADMINISTRAÇÃO PÚBLICA DEFESA E SEGURIDADE SOCIAL</fullName>
                <label>84..84 ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL</label>
            </value>
            <value>
                <fullName>85..85 EDUCAÇÃO</fullName>
            </value>
            <value>
                <fullName>86..88 SAÚDE HUMANA E SERVIÇOS SOCIAIS</fullName>
            </value>
            <value>
                <fullName>90..93 ARTES CULTURA ESPORTE E RECREAÇÃO</fullName>
                <label>90..93 ARTES, CULTURA, ESPORTE E RECREAÇÃO</label>
            </value>
            <value>
                <fullName>94..96 OUTRAS ATIVIDADES DE SERVIÇOS</fullName>
            </value>
            <value>
                <fullName>97..97 SERVIÇOS DOMÉSTICOS</fullName>
            </value>
            <value>
                <fullName>99..99 ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS</fullName>
            </value>
            <value>
                <fullName>Estudante</fullName>
            </value>
            <value>
                <fullName>Inapto</fullName>
            </value>
            <value>
                <fullName>ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL</fullName>
                <isActive>false</isActive>
                <label>ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL</label>
            </value>
            <value>
                <fullName>AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA</fullName>
                <isActive>false</isActive>
                <label>AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA</label>
            </value>
            <value>
                <fullName>ALOJAMENTO E ALIMENTAÇÃO</fullName>
                <isActive>false</isActive>
                <label>ALOJAMENTO E ALIMENTAÇÃO</label>
            </value>
            <value>
                <fullName>ARTES, CULTURA, ESPORTE E RECREAÇÃO</fullName>
                <isActive>false</isActive>
                <label>ARTES, CULTURA, ESPORTE E RECREAÇÃO</label>
            </value>
            <value>
                <fullName>ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES</fullName>
                <isActive>false</isActive>
                <label>ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES</label>
            </value>
            <value>
                <fullName>ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS</fullName>
                <isActive>false</isActive>
                <label>ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS</label>
            </value>
            <value>
                <fullName>ATIVIDADES IMOBILIÁRIAS</fullName>
                <isActive>false</isActive>
                <label>ATIVIDADES IMOBILIÁRIAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gerencia_Regional__c.field-meta.xml
<CustomField>
    <fullName>Gerencia_Regional__c</fullName>
    <label>Gerência Regional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gerencias_Regionais</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(VencimentoDoProximoContrato__c &gt; ADDMONTHS(TODAY(),1) ,&apos;Ativa&apos; , &apos;Inativa&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <label>Unidade de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia_Regional__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Unidades_de_Atendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Codigo_de_Reembolso__c/Codigo_de_Reembolso__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Código de Reembolso</label>
</CustomObject>

force-app/main/default/objects/Codigo_de_Reembolso__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/Despesa_e_Reembolso__c.object-meta.xml
<CustomObject>
    <label>Despesa e Reembolso</label>
    <nameField>
        <label>Nome de Despesa e Reembolso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas e Reembolsos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Check_in__c.field-meta.xml
<CustomField>
    <fullName>Check_in__c</fullName>
    <label>Check-in</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Despesas e Reembolsos</relationshipLabel>
    <relationshipName>Despesas_e_Reembolsos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Km__c.field-meta.xml
<CustomField>
    <fullName>Km__c</fullName>
    <inlineHelpText>Inserir os km que foram rodados e devem ser reembolsados. Obrigatório caso o tipo de reembolso seja &quot;Kilometragem&quot;</inlineHelpText>
    <label>Km</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>EnviadoParaRelatorio</fullName>
                <label>Enviado para o Relatório</label>
            </value>
            <value>
                <fullName>Recusado</fullName>
                <label>Recusado Pelo Gestor</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
                <label>Aprovado Pelo Gestor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Tipo_de_Despesa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Despesa__c</fullName>
    <label>Tipo de Despesa</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Despesa</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultor</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Gerente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CR__c.field-meta.xml
<CustomField>
    <fullName>CR__c</fullName>
    <label>CR</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Matricula__c.field-meta.xml
<CustomField>
    <fullName>Matricula__c</fullName>
    <label>Matrícula</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <defaultValue>&quot;Sao Paulo Capital&quot;</defaultValue>
    <label>Unidade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Administração Pública DF</fullName>
            </value>
            <value>
                <fullName>Agronegócio</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Aracaju</fullName>
            </value>
            <value>
                <fullName>Atendimento ao Cliente</fullName>
            </value>
            <value>
                <fullName>Barueri</fullName>
            </value>
            <value>
                <fullName>Bauru</fullName>
            </value>
            <value>
                <fullName>Camaçari</fullName>
            </value>
            <value>
                <fullName>Campinas</fullName>
            </value>
            <value>
                <fullName>Central Nacional de Licitações</fullName>
            </value>
            <value>
                <fullName>CIEE em Movimento</fullName>
            </value>
            <value>
                <fullName>CIEE One</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>Feira de Santana</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Fortaleza</fullName>
            </value>
            <value>
                <fullName>Goiás</fullName>
            </value>
            <value>
                <fullName>GR Centro-Oeste e Norte</fullName>
            </value>
            <value>
                <fullName>GR Grande SP e Capital</fullName>
            </value>
            <value>
                <fullName>GR Nordeste</fullName>
            </value>
            <value>
                <fullName>GR SP Interior e BH</fullName>
            </value>
            <value>
                <fullName>Guarulhos</fullName>
            </value>
            <value>
                <fullName>Inclusão Social</fullName>
            </value>
            <value>
                <fullName>Itabuna</fullName>
            </value>
            <value>
                <fullName>Itapetininga</fullName>
            </value>
            <value>
                <fullName>João Pessoa</fullName>
            </value>
            <value>
                <fullName>Juazeiro do Norte</fullName>
            </value>
            <value>
                <fullName>Jundiaí</fullName>
            </value>
            <value>
                <fullName>São Paulo Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Gerencias_Regionais.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>GR Grande São Paulo e Capital</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>GR SP Interior</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>GR Nordeste</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>GR Centro Oeste e Norte</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Ger CIEE Autônomo</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <isActive>false</isActive>
        <label>Ger Rio de Janeiro</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <isActive>false</isActive>
        <label>GR Norte</label>
    </customValue>
    <masterLabel>Gerências Regionais</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_de_Despesa.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>KM</fullName>
    </customValue>
    <customValue>
        <fullName>Outras despesas</fullName>
        <isActive>false</isActive>
        <label>Outras despesas</label>
    </customValue>
    <masterLabel>Tipo de Despesa</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DespesaRembolsoControllerTest.cls
@IsTest
public class DespesaRembolsoControllerTest {
    @TestSetup
    static void makeData() {
        Codigo_de_Reembolso__c codigoReembolso = new Codigo_de_Reembolso__c(Codigo__c = 300000);
        insert codigoReembolso;

        Account acc = new Account(
            Name = 'teste',
            BillingPostalCode = '01000-000',
            CNPJ_CPF__c = '12345678998',
            Unidade__c = '103',
            Gerencia_Regional__c = '1',
            CNAE__c = '01..03 AGRICULTURA PECUÁRIA PRODUÇÃO FLORESTAL PESCA E AQÜICULTURA',
            CNAE_Divisao__c = '01 AGRICULTURA PECUÁRIA E SERVIÇOS RELACIONADOS'
        );
        insert acc;

        Id idProfile = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator'].Id;
        User user = new User(
            Alias = 'standt',
            Email = 'standarduser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = idProfile,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'standarduser@cieetest.com',
            Unidade__c = 'São Paulo Capital',
            CPF__c = '12345678998',
            Matricula__c = '21321',
            CR__c = 'sadsa',
            Cargo__c = 'Consultor'
        );
        insert user;

        Despesa_e_Reembolso__c despesa = new Despesa_e_Reembolso__c(
            Name = 'Teste',
            Check_in__c = System.now(),
            Tipo_de_Despesa__c = 'KM',
            KM__c = 90,
            Status__c = 'Enviado_para_o_Relatorio',
            CreatedById = user.Id,
            Conta__c = acc.Id
        );
        insert despesa;
    }

    @IsTest
    public static void clonarTest() {
        Despesa_e_Reembolso__c despesa = [
            SELECT Id, Name, Check_in__c, Tipo_de_Despesa__c, KM__c, Status__c, CreatedById, Conta__c
            FROM Despesa_e_Reembolso__c
            LIMIT 1
        ];

        ApexPages.StandardController standardController = new ApexPages.StandardController(despesa);

        DespesasEReembolsoController controller = new DespesasEReembolsoController(standardController);
        Pagereference redirectPage = controller.clonar();
        
        Despesa_e_Reembolso__c clone = [
            SELECT Id, Name, Check_in__c, Tipo_de_Despesa__c, KM__c, Status__c, CreatedById, Conta__c
            FROM Despesa_e_Reembolso__c
            WHERE Name LIKE '%Clone'
        ];

        Assert.areEqual('/' + clone.Id, redirectPage.getUrl());
        Assert.areEqual('Teste - Clone', clone.Name);
        Assert.areEqual('Rascunho', clone.Status__c);
        Assert.areEqual(despesa.Check_In__c, clone.Check_In__c);
        Assert.areEqual(despesa.Tipo_de_Despesa__c, clone.Tipo_de_Despesa__c);
        Assert.areEqual(despesa.KM__c, clone.KM__c);
        Assert.areEqual(despesa.Conta__c, clone.Conta__c);
    }
}