force-app/main/default/objects/Despesa_e_Reembolso__c/Despesa_e_Reembolso__c.object-meta.xml
<CustomObject>
    <label>Despesa e Reembolso</label>
    <nameField>
        <label>Nome de Despesa e Reembolso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas e Reembolsos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Duracao_da_Visita__c.field-meta.xml
<CustomField>
    <fullName>Duracao_da_Visita__c</fullName>
    <label>Duração da Visita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>EnviadoParaRelatorio</fullName>
                <label>Enviado para o Relatório</label>
            </value>
            <value>
                <fullName>Recusado</fullName>
                <label>Recusado Pelo Gestor</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
                <label>Aprovado Pelo Gestor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DespesaReembolsoTriggerHandler.cls
public with sharing class DespesaReembolsoTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public static boolean IsFromBachJob ;
    public static boolean isFromUploadAPI = false;
    
    public DespesaReembolsoTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }

    public void OnBeforeInsert(List<Despesa_e_Reembolso__c> newList){
        for(Despesa_e_Reembolso__c despesa : newList){
            despesa.Duracao_da_Visita__c = '0';
        }
    }

    public void onBeforeUpdate(List<Despesa_e_Reembolso__c> newList, Map<Id, Despesa_e_Reembolso__c> mapOld){
        List<Profile> profs = [SELECT Id FROM Profile WHERE Id = :UserInfo.getProfileId() AND Name IN ('Supervisão', 'Gerência', 'System Administrator', 'Administrador do sistema')];        
        for(Despesa_e_Reembolso__c despesa : newList){
            Despesa_e_Reembolso__c despesaOld = mapOld.get(despesa.id);
            
            despesa.Duracao_da_Visita__c = '0';
            
            if(profs.isEmpty() || Test.isRunningTest()){
                if(despesaOld.Status__c == 'Aprovado' || despesaOld.Status__c == 'Recusado'){
                    despesa.addError('Você não pode editar esse registro no estágio atual.');
                }
            }           
        }
    }
}