force-app/main/default/objects/Despesa_e_Reembolso__c/Despesa_e_Reembolso__c.object-meta.xml
<CustomObject>
    <label>Despesa e Reembolso</label>
    <nameField>
        <label>Nome de Despesa e Reembolso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas e Reembolsos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa_e_Reembolso__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>EnviadoParaRelatorio</fullName>
                <label>Enviado para o Relatório</label>
            </value>
            <value>
                <fullName>Recusado</fullName>
                <label>Recusado Pelo Gestor</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
                <label>Aprovado Pelo Gestor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DespesasEReembolsoController.cls
public without sharing class DespesasEReembolsoController {
    private ApexPages.StandardSetController standardSetController;

    public List<Despesa_e_Reembolso__c> despesas { get; set; }

    public DespesasEReembolsoController(ApexPages.StandardController controller) {
        List<String> fieldsList = new List<String>();

        Map<String, Schema.SObjectField> fieldSchemaMap = Schema.getGlobalDescribe().get('Despesa_e_Reembolso__c').getDescribe().fields.getMap();

        for (String fieldName : fieldSchemaMap.keySet()) {
            Schema.DescribeFieldResult fieldDescribe = fieldSchemaMap.get(fieldName).getDescribe();

            if (fieldDescribe.isCreateable()) {
                fieldsList.add(fieldName);
            }
        }

        despesas = Database.Query(
            'SELECT ' + String.join(fieldsList, ', ') + ' FROM Despesa_e_Reembolso__c WHERE Id = \'' + controller.getId() + '\''
        );
    }

    public PageReference clonar() {
        Despesa_e_Reembolso__c clone = despesas[0].clone(false, true, false, true);
        clone.Status__c = 'Rascunho';
        clone.Name += ' - Clone';
        insert clone;

        PageReference redirectPage = new PageReference('/' + clone.Id);
        redirectPage.setRedirect(true);
        return redirectPage;
    }
}