force-app/main/default/objects/Distribuicao_Lead__c/Distribuicao_Lead__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Distribuição Lead</label>
</CustomObject>

force-app/main/default/objects/Distribuicao_Lead__c/fields/Contador__c.field-meta.xml
<CustomField>
    <fullName>Contador__c</fullName>
    <label>Contador</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Gerencia_Regional__c.field-meta.xml
<CustomField>
    <fullName>Gerencia_Regional__c</fullName>
    <label>Gerência Regional</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gerencias_Regionais</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/NomeDaCampanha__c.field-meta.xml
<CustomField>
    <fullName>NomeDaCampanha__c</fullName>
    <label>Nome da Campanha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Selecionar este campo quando o lead for encaminhado para alguma Unidade.</inlineHelpText>
    <label>Unidade</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Unidades_de_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Unidades_de_Atendimento__c</fullName>
    <label>Unidade de Atendimento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia_Regional__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Unidades_de_Atendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <defaultValue>&quot;Sao Paulo Capital&quot;</defaultValue>
    <label>Unidade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Administração Pública DF</fullName>
            </value>
            <value>
                <fullName>Agronegócio</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Aracaju</fullName>
            </value>
            <value>
                <fullName>Atendimento ao Cliente</fullName>
            </value>
            <value>
                <fullName>Barueri</fullName>
            </value>
            <value>
                <fullName>Bauru</fullName>
            </value>
            <value>
                <fullName>Camaçari</fullName>
            </value>
            <value>
                <fullName>Campinas</fullName>
            </value>
            <value>
                <fullName>Central Nacional de Licitações</fullName>
            </value>
            <value>
                <fullName>CIEE em Movimento</fullName>
            </value>
            <value>
                <fullName>CIEE One</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>Feira de Santana</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Fortaleza</fullName>
            </value>
            <value>
                <fullName>Goiás</fullName>
            </value>
            <value>
                <fullName>GR Centro-Oeste e Norte</fullName>
            </value>
            <value>
                <fullName>GR Grande SP e Capital</fullName>
            </value>
            <value>
                <fullName>GR Nordeste</fullName>
            </value>
            <value>
                <fullName>GR SP Interior e BH</fullName>
            </value>
            <value>
                <fullName>Guarulhos</fullName>
            </value>
            <value>
                <fullName>Inclusão Social</fullName>
            </value>
            <value>
                <fullName>Itabuna</fullName>
            </value>
            <value>
                <fullName>Itapetininga</fullName>
            </value>
            <value>
                <fullName>João Pessoa</fullName>
            </value>
            <value>
                <fullName>Juazeiro do Norte</fullName>
            </value>
            <value>
                <fullName>Jundiaí</fullName>
            </value>
            <value>
                <fullName>São Paulo Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Gerencias_Regionais.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>GR Grande São Paulo e Capital</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>GR SP Interior</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>GR Nordeste</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>GR Centro Oeste e Norte</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Ger CIEE Autônomo</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <isActive>false</isActive>
        <label>Ger Rio de Janeiro</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <isActive>false</isActive>
        <label>GR Norte</label>
    </customValue>
    <masterLabel>Gerências Regionais</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TesteTriggerLead.cls
@isTest
public class TesteTriggerLead {
    @isTest
    public static void createData() {
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'Usuário Padrão' OR Name = 'Standard User' LIMIT 1].Id;
        Distribuicao_Lead__c d = new Distribuicao_Lead__c(Contador__c = 0);
        User u = new User(
            Alias = 'stand4',
            Email = 'standarduser4@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing123',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = profileId,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'standarduser@cieetest.com',
            Unidade__c = 'São Paulo Capital'
        );
        
		List<Lead> testLeads = new List<Lead>();
        for (Integer i = 0; i < 5; i++) {
   			Lead lead = new Lead();
            lead.FirstName = 'Test';
            lead.LastName = 'Lead' + i;
			lead.Status = 'Novo';
            lead.Company = 'teste';
            lead.PostalCode = '00001-000';
            lead.Unidades_de_Atendimento__c = '101';
            lead.Gerencia_Regional__c = '1';
//            lead.NomeDaCampanha__c = 'Expo';  
//            lead.Atribuir_a_mim__c = false;
            testLeads.add(lead);
        }        
//        insert testLeads;

        
        for (Lead lead : testLeads) {
            //System.assertEquals(true, lead.OwnerId != null, 'OwnerId não foi definido corretamente');
            System.assertEquals('Test', lead.FirstName);
        }        
    }
    
   @isTest 
   public static void testAfterInsert() {
		List<Lead> testLeads = new List<Lead>();
        for (Integer i = 0; i < 5; i++) {
   			Lead lead = new Lead();
            lead.FirstName = 'Test';
            lead.LastName = 'Lead' + i;
			lead.Status = 'Novo';
            lead.Company = 'teste';
            lead.PostalCode = '00001-000';
            lead.Unidades_de_Atendimento__c = '101';
            lead.Gerencia_Regional__c = '1';
            testLeads.add(lead);
        }                
        Test.startTest();
        insert testLeads;
        Test.stopTest();
        for (Lead lead : testLeads) {
            //System.assertEquals(true, lead.OwnerId != null, 'OwnerId não foi definido corretamente');
            System.assertEquals('Test', lead.FirstName);
        }      
    }
}